name: spotify_auth_proxy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: kohlerdominik/docker-run-action@v1
      with:
        image: ghcr.io/conradludgate/spotify-auth-proxy
        environment: |
          SPOTIFY_CLIENT_REDIRECT_URI={curl $url}/spotify_callback
        options: |
          --env-file ./.env
        run: |
          echo SPOTIFY_CLIENT_REDIRECT_URI
          --rm -it -p 27228:27228